config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("super_zapatos.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^stores/', include("super_zapatos.stores.stores_urls", namespace="stores")),
    url(r'^articles/', include("super_zapatos.stores.articles_urls", namespace="articles")),
    url(r'^services/', include("super_zapatos.api.urls", namespace="api")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

super_zapatos/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [

    url(
        r'^stores/?$',
        view=views.StoreListApiView.as_view(),
        name='list'
    ),
    url(
        r'^articles/?$',
        view=views.ArticleListApiView.as_view(),
        name='articles_list'
    ),
    url(
        r'^articles/stores/(?P<pk>\w+)/?$',
        view=views.ArticleStoreListApiView.as_view(),
        name='articles_store_list'
    ),


]

super_zapatos/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

super_zapatos/api/models.py
from django.db import models

# Create your models here.

super_zapatos/stores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Store(models.Model):
    """
    This model represents the store table and objects
    """
    name = models.CharField(_("Name of Store"), max_length=255, default='')
    address = models.CharField(_("Address of Store"), max_length=255, default='')

    class Meta:
        db_table = 'stores'
        verbose_name = 'store'
        verbose_name_plural = 'stores'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('stores:detail', kwargs={'pk': self.pk})


@python_2_unicode_compatible
class Article(models.Model):
    """
    This model represents the article table and objects
    """
    name = models.CharField(_("Name of Article"), max_length=255, default='')
    description = models.TextField(_("Description"), default='')
    price = models.PositiveIntegerField(_("Price"))
    total_in_shelf = models.PositiveIntegerField(_("Total in Shelf"))
    total_in_vault = models.PositiveIntegerField(_("total in Vault"))
    store = models.ForeignKey(Store, related_name='articles')

    class Meta:
        db_table = 'articles'
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'pk': self.pk})

super_zapatos/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

super_zapatos/api/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import logging

from django.http import Http404

from rest_framework import generics
from rest_framework.exceptions import ParseError

from .mixins import BasicAuthenticationMixin
from super_zapatos.stores import serializers
from super_zapatos.stores import models

logger = logging.getLogger(__name__)


class StoreListApiView(BasicAuthenticationMixin, generics.ListAPIView):
    """
    This is the store list for the API services
    """
    queryset = models.Store.objects.all()
    serializer_class = serializers.StoreSerializer


class ArticleListApiView(BasicAuthenticationMixin, generics.ListAPIView):
    """
    This is the article list for the API services
    """
    queryset = models.Article.objects.all()
    serializer_class = serializers.ArticleSerializer


class ArticleStoreListApiView(BasicAuthenticationMixin, generics.ListAPIView):
    """
    This is the article per store list for the API services
    """
    queryset = models.Article.objects.all()
    serializer_class = serializers.ArticleSerializer

    def get_queryset(self):
        queryset = super(ArticleStoreListApiView, self).get_queryset()
        pk = self.kwargs.get(self.lookup_field)
        try:
            pk = int(pk)
            queryset = queryset.filter(store__pk=pk)
            if queryset:
                return queryset
            else:
                raise Http404
        except ValueError:
            raise ParseError

super_zapatos/stores/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView


from .models import Store, Article
from .mixins import StoreArticleListMixin


class StoreListView(ListView):
    """
    This is the Store list view
    """
    model = Store
    template_name = 'stores/store_list.html'


class StoreCreateView(CreateView):
    """
    This is the Store create view
    """
    model = Store
    fields = ['name', 'address']
    template_name = 'stores/store_form.html'
    success_url = reverse_lazy('stores:list')


class StoreDetailView(DetailView):
    """
    This is the Store detail view
    """
    model = Store
    template_name = 'stores/store_detail.html'


class StoreUpdateView(UpdateView):
    """
    This is the Store update view
    """
    model = Store
    fields = ['name', 'address']
    template_name = 'stores/store_form.html'


class ArticleListView(ListView):
    """
    This is the Article list view
    """
    model = Article
    template_name = 'stores/article_list.html'


class ArticleCreateView(CreateView):
    """
    This is the Article create view
    """
    model = Article
    template_name = 'stores/article_form.html'
    fields = ['name', 'description', 'price', 'total_in_shelf', 'total_in_vault', 'store']


class ArticleDetailView(DetailView):
    """
    This is the Article detail view
    """
    model = Article
    template_name = 'stores/article_detail.html'


class ArticleUpdateView(UpdateView):
    """
    This is the Article update view
    """
    model = Article
    template_name = 'stores/article_form.html'
    fields = ['name', 'description', 'price', 'total_in_shelf', 'total_in_vault', 'store']


class StoreArticlesListView(StoreArticleListMixin, ListView):
    """
    This is the Article per Store list view
    """
    model = Article
    template_name = 'stores/store_article_list.html'

super_zapatos/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

super_zapatos/templates/stores/article_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Article: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
        <p>Article Name: {{ object.name }}</p>
        <p>Description: {{ object.description }}</p>
        <p>Price: {{ object.price }}</p>
        <p>Total in Shelf: {{ object.total_in_shelf }}</p>
        <p>Total in Vault: {{ object.total_in_vault }}</p>
        <p><a href="{% url 'articles:update' object.pk %}">Update Article</a></p>
    </div>
  </div>

</div>
{% endblock content %}

super_zapatos/templates/stores/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Store: {{ store.name }} Create New Article{% endblock %}

{% block content %}
    <h1>Store: {{ store.name }} Create New Article</h1>
    <div class="row">
        <div class="col-md-9">
            <form class="form-horizontal" method="post" action=".">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Send</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

super_zapatos/templates/stores/article_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Articles{% endblock %}

{% block content %}

<div class="container">

    <h2>Articles</h2>

    <div class="list-group">
        {% for article in object_list %}
          <a href="{% url 'articles:detail' article.pk %}" class="list-group-item">
            <h4 class="list-group-item-heading">Article: {{ article.name }} -- Store: {{ article.store.name }}</h4>
          </a>
        {% empty %}
            There are not articles, click on link below to start add.
        {% endfor %}
        <br>
        <a href="{% url 'articles:create' %}">Add Article</a>
    </div>
</div>
{% endblock content %}

super_zapatos/templates/stores/store_article_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Store: {{ store.name }} - Articles{% endblock %}

{% block content %}

<div class="container">

    <h2>Store: {{ store.name }} - Articles</h2>

    <div class="list-group">
        {% for article in object_list %}
          <a href="{% url 'articles:detail' article.pk %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ article.name }}</h4>
          </a>
        {% empty %}
            There are not articles, click on link below to start add.
        {% endfor %}
        <br>
        <a href="{% url 'articles:create' %}">Add Article</a>
    </div>
</div>
{% endblock content %}

super_zapatos/templates/stores/store_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Store: {{ object.name }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
        <p>Store Name: {{ object.name }}</p>
        <p>Store Address: {{ object.address }}</p>
        <p><a href="{% url 'stores:update' object.pk %}">Update Store</a></p>
        <p><a href="{% url 'articles:stores' object.pk %}">See Store Articles</a></p>
    </div>
  </div>


</div>
{% endblock content %}

super_zapatos/templates/stores/store_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create New Store{% endblock %}

{% block content %}
    <h1>Create New Store</h1>
    <form class="form-horizontal" method="post" action=".">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Send</button>
          </div>
        </div>
    </form>
{% endblock %}

super_zapatos/templates/stores/store_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Stores{% endblock %}

{% block content %}

<div class="container">

    <h2>Stores</h2>

    <div class="list-group">
        {% for store in object_list %}
          <a href="{% url 'stores:detail' store.pk %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ store.name }}</h4>
          </a>
        {% endfor %}
        <br>
        <a href="{% url 'stores:create' %}">Add Store</a>
    </div>
</div>
{% endblock content %}